# See https://docs.github.com/en/actions/guides/building-and-testing-python
# 2020-02-20 slg - For Dreamhost, we are now using Python 3.9 and Ubuntu-18.04
name: CI (pip)
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']   # with MySQL service, we now only run on ubuntu
        python-version: [3.11]   # installed version on Dreamhost
    runs-on: ${{ matrix.os }}
    services:
      # https://stackoverflow.com/questions/72294279/how-to-connect-to-mysql-databas-using-github-actions
      mysql:
        image: mysql:8.0
        env:
          # The MySQL docker container requires these environment variables to be set
          # so we can create and migrate the test database.
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: testrootpass
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Configure ubuntu with ffmpeg"
        if: startsWith(matrix.os, 'ubuntu')
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: "Configure ubuntu"
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          make install-ubuntu

      - name: "Configure MacOS"
        if: startsWith(matrix.os, 'macos')
        run: |
          make install-macos

      - name: "Configure Windows"
        if: startsWith(matrix.os, 'windows')
        run: |
          make install-windows

      - name: Update GITHUB_PATH and install dependencies
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          make install-python-dependencies

      - name: Lint with pylint
        run: |
          make pylint

      - name: Test with pytest and a functioning database (but only on Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        env:
          SKIP_ENDPOINT_TEST:   ${{ vars.SKIP_ENDPOINT_TEST }}
          TEST_USER_EMAIL:  ${{ vars.TEST_USER_EMAIl }}
          TEST_USER_APIKEY: ${{ secrets.TEST_USER_APIKEY }}
          MYSQL_HOST:       ${{ secrets.MYSQL_HOST }}
          MYSQL_DATABASE:   ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER:       ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD:   ${{ secrets.MYSQL_PASSWORD }}
          SMTP_USERNAME:    ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD:    ${{ secrets.SMTP_PASSWORD }}
          SMTP_SERVER:      ${{ secrets.SMTP_SERVER }}
          SMTP_PORT:        ${{ secrets.SMTP_PORT }}
          IMAP_USERNAME:    ${{ secrets.IMAP_USERNAME }}
          IMAP_PASSWORD:    ${{ secrets.IMAP_PASSWORD }}
          IMAP_SERVER:      ${{ secrets.IMAP_SERVER }}

        run: |
          cp -v etc/github_actions_mysql_rootconfig.ini $HOME
          export
          make create_localdb
          make coverage
          make remove_localdb
          ls -l

      - name: Upload to codecov.io
        if: startsWith(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
