# See https://docs.github.com/en/actions/guides/building-and-testing-python
# 2020-02-20 slg - For Dreamhost, we are now using Python 3.9 and Ubuntu-18.04
name: CI (pip)
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: [3.9]   # installed version on Dreamhost
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Configure MacOS"
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libmagic

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update GITHUB_PATH and install dependencies
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          make install-dependencies

      - name: Lint with pylint
        run: |
          make pylint

      - name: Test with pytest and a functioning database (but only on Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        env:
          TEST_ENDPOINT:    ${{ env.TEST_ENDPOINT }}
          TEST_USER_APIKEY: ${{ secrets.TEST_USER_APIKEY }}
          MYSQL_HOST:       ${{ secrets.MYSQL_HOST }}
          MYSQL_DATABASE:   ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER:       ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD:   ${{ secrets.MYSQL_PASSWORD }}
        run: |
          printenv | sort
          pip install pytest
          make coverage

      - name: Upload to codecov.io
        if: startsWith(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        with:
          verbose: true
