# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
name: Deploy
concurrency: production

on:
  pull_request:
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Deploy to dev.plannttracer"
        run: |
          APP_HOST=dev.planttracer.com
          SSH_USER=planttracer
          eval $(ssh-agent)
          base64 -d <<< "${{ secrets.PT_SSH_BASE64 }}" | ssh-add  -
          ssh-add -l
          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $SSH_USER@$APP_HOST "hostname; pwd; ls -l ; cd $APP_HOST; git checkout main && git pull --recurse-submodules && make install-dependencies && make touch"
