# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged

name: Deploy

concurrency: production

on:
  pull_request:
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        eval $(ssh-agent)
        echo "${{ secrets.PTMANAGER_SSH_KEY }}" | tr -d '\r' | ssh-add -
        ssh-add -l
        ssh -o GlobalKnownHostsFile=etc/known_hosts brennerbotany@app.planttracer.com 'cd app.planttracer.com;git pull'
        echo The PR has been merged
