# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
name: Deploy to Production
concurrency: production

on:
  pull_request:
    types: [closed]

env:
  PROD_USER: ${{ secrets.PROD_USER }}
  PROD_HOST: app.planttracer.com
  DEMO_USER: ${{ secrets.DEMO_USER }}
  DEMO_HOST: demo.planttracer.com

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Load Credentials"
        run: |
          eval $(ssh-agent)
          base64 -d <<< "${{ secrets.PT_SSH_BASE64 }}" | ssh-add  -
          ssh-add -l

      - name: "Deploy to prod"
        run: |
          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $PROD_USER@$PROD_HOST \
             "cd $PROD_HOST; python3 --version && git checkout main && git pull --recurse-submodules && make install-ubuntu && make touch && make pytest"

      - name: "Deploy to demo"
        run: |
          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $DEMO_USER@$DEMO_HOST \
             "cd $DEMO_HOST; python3 --version && git checkout main && git pull --recurse-submodules && make install-ubuntu && make touch && make pytest"
