# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
name: Deploy
concurrency: production

on:
  pull_request:
    types: [closed]

env:
  SSH_USER: plantdev
  APP_HOST: dev.planttracer.com

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Deploy to dev.plannttracer"
        run: |
          eval $(ssh-agent)
          base64 -d <<< "${{ secrets.PT_SSH_BASE64 }}" | ssh-add  -
          ssh-add -l
          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $SSH_USER@$APP_HOST "python3 --version; hostname; pwd; ls -l"
          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $SSH_USER@$APP_HOST "cd $APP_HOST; git checkout main && git pull --recurse-submodules && make install-python-dependencies && make touch"
          ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $SSH_USER@$APP_HOST "source \$HOME/plant_dev.bash ; cd $APP_HOST; make pytest"
