# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged

name: Deploy

concurrency: production

on:
  pull_request:
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        APP_HOST=app.planttracer.com
        SSH_USER=planttracer
        eval $(ssh-agent)
        echo ${{ secrets.PT_SSH_BASE64 }} | openssl base64 -d > .sshkey
        wc -l .sshkey
        ssh-add .sshkey
        ssh-add -l
        /bin/rm -f .sshkey
        ssh -o GlobalKnownHostsFile=etc/known_hosts $SSH_USER@$APP_HOST "hostname;cd $APP_HOST;git pull"
        echo The PR has been merged
