# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged

name: Deploy

concurrency: production

on:
  pull_request:
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        APP_HOST=app.planttracer.com
        SSH_USER=planttracer
        eval $(ssh-agent)
        echo "${{ secrets.PTMANAGER_SSH_KEY }}" > .sshkey
        wc -l .sshkey
        openssl sha1 .sshkey
        cat .sshkey | ssh-add -
        ssh-add -l
        ssh -o GlobalKnownHostsFile=etc/known_hosts $SSH_USER@$APP_HOST "cd $APP_HOST;git pull"
        echo The PR has been merged
