# See https://stackoverflow.com/questions/60710209/trigger-github-actions-only-when-pr-is-merged
name: Deploy to app.planttracer.com
concurrency: deploy-production

on:
  pull_request:
    types: [closed]

env:
  REMOTE_USER: ${{ secrets.PROD_USER }}
  REMOTE_HOST: app.planttracer.com
  BRANCH: deploy-dreamhost

jobs:
  if_deploy_dreamhost:
    if: github.ref == 'refs/heads/deploy-dreamhost'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Load credentials"
        run: |
          mkdir $HOME/.ssh
          chmod 700 $HOME/.ssh
          base64 -d <<< "${{ secrets.PLANTTRACER_DEPLOY_PUB_BASE65 }}" > $HOME/.ssh/newkey
          chmod 600 $HOME/.ssh/newkey

      - name: "Deploy to production"
        run: |
          bash etc/deploy-dreamhost.bash \
          "-i $HOME/.ssh/newkey -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=etc/known_hosts $REMOTE_USER@$REMOTE_HOST" \
          $REMOTE_HOST $BRANCH
